// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'item-comment': string;
  'item-comment__author': string;
  'item-comment__date': string;
  'item-comment__header': string;
  'item-comment__messages': string;
}
export const cssExports: CssExports;
export default cssExports;
