// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'layout': string;
  'layout__content': string;
  'layout__header': string;
}
export const cssExports: CssExports;
export default cssExports;
