// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'leader-board': string;
  'leader-board__header': string;
  'leader-board__header_title': string;
  'leader-board__info': string;
}
export const cssExports: CssExports;
export default cssExports;
