// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'leader-board': string;
  'leader-board_header': string;
  'leader-board_header_title': string;
  'leader-board_info': string;
}
export const cssExports: CssExports;
export default cssExports;
