// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'instruction__leading-block': string;
  'round-intro': string;
  'round-intro__button': string;
  'round-intro__instruction': string;
  'round-intro__round-count': string;
  'round-intro__round-count_all': string;
}
export const cssExports: CssExports;
export default cssExports;
