// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'player-selection-page': string;
  'player-selection-page__card': string;
  'player-selection-page__cards': string;
  'player-selection-page__title': string;
}
export const cssExports: CssExports;
export default cssExports;
