// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'item-status': string;
  'item-status__avatar': string;
  'item-status__name': string;
  'item-status__role': string;
  'item-status__status': string;
  'sp': string;
  'sp__body': string;
  'sp__item': string;
  'sp__title': string;
}
export const cssExports: CssExports;
export default cssExports;
