// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'avatar': string;
  'avatar_token': string;
  'login': string;
  'login_form': string;
}
export const cssExports: CssExports;
export default cssExports;
