// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'btn': string;
  'btn__large': string;
  'btn__medium': string;
  'btn__primary': string;
  'btn__secondary': string;
  'btn__small': string;
}
export const cssExports: CssExports;
export default cssExports;
