// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'navbar': string;
  'navbar__links': string;
}
export const cssExports: CssExports;
export default cssExports;
