// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'lds-ripple': string;
  'preloader': string;
}
export const cssExports: CssExports;
export default cssExports;
