// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'mblock': string;
  'mblock_figures': string;
  'mblock_figures-entering': string;
  'mblock_figures-exiting': string;
}
export const cssExports: CssExports;
export default cssExports;
