// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'item-theme': string;
  'item-theme__delete': string;
  'item-theme__wrapper': string;
}
export const cssExports: CssExports;
export default cssExports;
