// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'forum': string;
  'forum__left': string;
  'forum__right': string;
  'forum__themes': string;
  'forum__wc': string;
  'forum__wc-button': string;
  'forum__wc-control': string;
  'forum__wc-header': string;
  'forum__wc-messages': string;
  'forum__wc-wrapper-messages': string;
  'forum__wrapper-search': string;
  'forum__wrapper-theme': string;
}
export const cssExports: CssExports;
export default cssExports;
