// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'canvas': string;
  'card': string;
  'card__choisen': string;
  'cards': string;
}
export const cssExports: CssExports;
export default cssExports;
