// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'lb_avatar': string;
  'lb_block': string;
  'lb_login': string;
  'lb_row': string;
  'lb_score': string;
}
export const cssExports: CssExports;
export default cssExports;
