// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'lb__avatar': string;
  'lb__block': string;
  'lb__login': string;
  'lb__row': string;
  'lb__score': string;
}
export const cssExports: CssExports;
export default cssExports;
