// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'landing-info': string;
  'page-404': string;
  'page-404__subtitle': string;
  'page-404__title': string;
}
export const cssExports: CssExports;
export default cssExports;
