// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'player-selection-page': string;
  'player-selection-page__card': string;
  'player-selection-page__cards': string;
  'player-selection-page__desc': string;
  'player-selection-page__input': string;
  'player-selection-page__label': string;
  'player-selection-page__title': string;
  'player-selection-page__wrapper-input': string;
}
export const cssExports: CssExports;
export default cssExports;
