// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'fw': string;
  'fw_buttons': string;
  'fw_buttons__main': string;
  'fw_buttons__secondary': string;
  'fw_formError': string;
  'fw_header': string;
  'fw_header__link': string;
}
export const cssExports: CssExports;
export default cssExports;
