// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'tf': string;
  'tf_input': string;
  'tf_input__error': string;
  'tf_label': string;
  'tf_label__error': string;
  'tf_textError': string;
}
export const cssExports: CssExports;
export default cssExports;
