// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'header': string;
  'header_emptyAva': string;
  'header_logo': string;
}
export const cssExports: CssExports;
export default cssExports;
