name: Testing project

on:
  push:
    branches:
      - 'feature/**'
  
  pull_request:
    branches:
      - master
      - deploy
      - 'sprint_**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 16
        cache: 'npm'
        
    - name: Install modules
      run: npm install -f
    - name: Run tests
      run: npm run test
 
