name: Testing project

on:
  push:
    branches:
      - 'feature/**'
jobs:
  build:
    runs-on: node:latest
    steps:
      - uses: actions/checkout@v2
      - name: Install modules
        run: npm install
      - name: Run tests
        run: npm run test
 
